Classes and objects
DZemitis/c-sharp-syllabus pull request #7
Opened 2021-12-10 12:50 UTC by DZemitis

2021-12-10 19:43 UTC, ausmoons requested changes

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/EnergyDrinks/Program.cs
> +
Pietiek ar vienu tukšu rindu, ja gribi atdalīt

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 1/Product.cs
> +
Lieka tukša rinda

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 1/Product.cs
> +        private string _name { get; set; }
Private nav { get; set; }

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 1/Program.cs
> +            foreach (var prod in products)
Vajag tukšu rindu pēc }

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3/Program.cs
> +        {
?

2021-12-10 19:43 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3a/FuelGauge.cs
> +        }
Vajag tukšu rindu pēc }

2021-12-10 20:53 UTC, DZemitis commented on csharp-basics/exercises/ClassesAndObjects/Exercise 3/Program.cs
> +        {
es biju uztaisījis trešajam uzdevumam jaunu failu, un sanāca gan 3, gan 3a, izdzēsu no VS, bet lokāli man viņš laikam vēl palika, es viņu tagad izdzēsu, un tad sanāk paliek tikai 3a, piedošan, es nesapratu kā īsti tas strādā, tagad, laikam, skaidrība.

2021-12-12 08:29 UTC, ausmoons approved these changes

2021-12-12 10:15 UTC, merged